<a href="https://colab.research.google.com/github/shubham4375/Test/blob/main/Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#numpy
import numpy as np

Creating Arrays

In [3]:
np.array([1,2,3]) #| One Dimentional Array

array([1, 2, 3])

In [4]:
np.array([(1,2,3),(4,5,6)]) #| Two Dimentional Array 2*3

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.zeros(3) #| 1D array of length 3 all values 0.0

array([0., 0., 0.])

In [6]:
np.ones((3,4)) #| 3*4 array with all values 1.0

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [8]:
np.eye(5) #| Identity Matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [10]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [11]:
np.random.rand(4,5)

array([[0.47136129, 0.95353918, 0.77177849, 0.65328615, 0.15166066],
       [0.72426054, 0.334161  , 0.98965909, 0.62991555, 0.94754789],
       [0.57301202, 0.36249546, 0.54952683, 0.38634322, 0.48880968],
       [0.32581971, 0.18338846, 0.57458051, 0.94240911, 0.37578103]])

In [12]:
np.random.rand(6,7)*100

array([[83.11698648, 34.88978924, 86.5093727 ,  8.91097273, 89.52465182,
        10.30815065,  2.94990284],
       [45.5100155 ,  4.27312961, 84.67162305, 49.26587963, 45.9079281 ,
        36.11292485, 62.91191359],
       [87.72438153, 34.17219005, 76.57813424, 77.38970959, 44.04030525,
        10.47645062, 49.41410947],
       [89.86264497, 40.83709966, 95.21662399, 21.76770781, 37.74494741,
        96.68465707, 32.79679789],
       [14.40617601, 99.77801801, 99.60387164, 98.30358046, 95.82768586,
        80.39905475, 95.16730384],
       [26.36409415, 87.47363428, 30.41815295,  0.81575345, 99.25193352,
         5.34648284, 14.32800874]])

In [13]:
np.random.randint(5,size=(2,3)) #0-4 random int

array([[0, 1, 2],
       [3, 1, 2]])

Inspecting Properties

In [14]:
# arr.size | Returns number of elements with array
# arr.shape | Returns dimention of arr (rows,columns)
# arr.dtype | Returns type of elements in arr
# arr.astype(dtype) | convert arr elements to type dtype
# arr.tolist() | convert arr to a python list
# np.info(np.eye) | view documentation for np.eye

Copying/sorting/reshaping

In [15]:
# np.copy(arr) | copies arr to new memory
# arr.view(dtype) | creates view of arr elements with type dtype
# arr.sort() | sorts arr
# arr.sort(axis=0) | Sorts specific axis of arr
# two_d_arr.flatten() | Flattens 2D array two_d_arr to 1D
# arr.T | Transposes arr (rows become columns and vice versa)
# arr.reshape(3,4) | Reshapes arr to 3 rows, 4 columns without changing data
# np.resize(arr,(5,6)) | changes arr shape to 5*6 and fills new values with 0

In [16]:
arr = np.array([1, 2, 3])
np.copy(arr)

array([1, 2, 3])

In [17]:
arr.sort()

In [18]:
arr.sort(axis=0)

In [19]:
arr

array([1, 2, 3])

In [20]:
np.resize(arr,(5,6))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

Adding/removing elements

In [21]:
# np.append(arr,values) | apeends values to end of arr
# np.insert(arr,2,values) | Inserts values into arr before index 2
# np.delete(arr,3,axis=0) | Delete row on index 3 of arr
# np.delete(arr,4,axis=1) | Deletes column on index 4 of arr

In [22]:
np.append(arr,(4,5,6))

array([1, 2, 3, 4, 5, 6])

In [23]:
np.insert(arr,2,7)

array([1, 2, 7, 3])

In [24]:
np.delete(arr,2,axis=0)

array([1, 2])

Combining/splitting

In [25]:
# np.concatenate((arr1,arr2),axis=0) | Adds arr2 aas rows to the end of arr1
# np.concatenate((arr1,arr2),axis=1) | Adds arr2 as columns to end of arr1
# np.split(arr,3) | Splits arr into 3 sub-arrays
# np.hsplit(arr,5) | Splits arr horizontally on the 5th index

In [26]:
a=np.array([1,2,3])
b=np.array([2,3,1])
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
np.split(a,3)

[array([1]), array([2]), array([3])]

In [28]:
np.split(c,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [29]:
np.hsplit(c,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [30]:
np.vsplit(c,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [31]:
# Extract specific items from an array?
list2 = [[1,2,3,4],[3,4,5,6],[5,6,7,8]]
arr2 = np.array(list2)
arr2

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [32]:
arr2.shape

(3, 4)

In [33]:
arr2.dtype

dtype('int64')

In [34]:
arr2.reshape((4,3))

array([[1, 2, 3],
       [4, 3, 4],
       [5, 6, 5],
       [6, 7, 8]])

In [35]:
arr2

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [36]:
arr2[:3,:2]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
b=arr2>4
b

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [38]:
arr2[b]

array([5, 6, 5, 6, 7, 8])

In [39]:
# how to reverse the rows and the whole array?

In [40]:
arr2[::-1] # reverse the row posi

array([[5, 6, 7, 8],
       [3, 4, 5, 6],
       [1, 2, 3, 4]])

In [41]:
arr2[::-1,::-1] # reverse the row and column posi

array([[8, 7, 6, 5],
       [6, 5, 4, 3],
       [4, 3, 2, 1]])

In [42]:
arr2 = arr2.astype('float')
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [43]:
# how to represent misiing values and infinite ?

In [44]:
# insert a nan and an inf
arr2[1,1] = np.nan # not a number
arr2[1,2] = np.inf # infinite

In [45]:
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., nan, inf,  6.],
       [ 5.,  6.,  7.,  8.]])

In [46]:
# replace nan and inf with -1. don't use arr2 == np.nan
missing_bool = np.isnan(arr2) | np.isinf(arr2)
arr2[missing_bool] = -1
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [47]:
# how to compute mean, min, mac on the ndarray?
# mean, max and min
print("mean value is : ", arr2.mean())
print("max value is : ",arr2.max())
print("min va;ue is : ",arr2.min())
# cumulative sum
print(np.cumsum(arr2))

mean value is :  3.5833333333333335
max value is :  8.0
min va;ue is :  -1.0
[ 1.  3.  6. 10. 13. 12. 11. 17. 22. 28. 35. 43.]


In [48]:
# how to create a new array from an existing array?
#  assign portion of arr2 to arr2a. Doesn't really create a new array.
arr2a = arr2[:2, :2]
print(arr2a)
arr2a[:1, :1] = 100 # 100 will reflect in arr2
arr2, arr2a

[[ 1.  2.]
 [ 3. -1.]]


(array([[100.,   2.,   3.,   4.],
        [  3.,  -1.,  -1.,   6.],
        [  5.,   6.,   7.,   8.]]),
 array([[100.,   2.],
        [  3.,  -1.]]))

# Reshaping and flattening multidimensional arrays

In [49]:
# reshape a 3*4 array to 4*3 array
arr2.reshape(4, 3)

array([[100.,   2.,   3.],
       [  4.,   3.,  -1.],
       [ -1.,   6.,   5.],
       [  6.,   7.,   8.]])

# What is the difference between flatten( and ravel()?
The difference between ravel and flatten is, the new array created using ravel is actually a reference to the parent array. so, any changes to the new array will affect the parent as well. but is memory efficent since it does not create a copy.

In [50]:
#Flatten it to a 1D array
arr2.flatten()

array([100.,   2.,   3.,   4.,   3.,  -1.,  -1.,   6.,   5.,   6.,   7.,
         8.])

In [52]:
#changing the flattened array does not change parent
b1 = arr2.flatten()

b1[0] = 200 # changing b1 does not affect arr2
print(b1)
arr2

[200.   2.   3.   4.   3.  -1.  -1.   6.   5.   6.   7.   8.]


array([[100.,   2.,   3.,   4.],
       [  3.,  -1.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [53]:
# Changing the raveled array changes the aprent aslo.
print(arr2.ravel())
b2 = arr2.ravel()
b2[0] = 101 # Changing b2 changes arr2 also
arr2

[100.   2.   3.   4.   3.  -1.  -1.   6.   5.   6.   7.   8.]


array([[101.,   2.,   3.,   4.],
       [  3.,  -1.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

# How to Create sequences, repetitions and random numbers using numpy?

In [56]:
# lower limit is 0 by default
print(np.arange(5))
# 0to 9
print(np.arange(0, 10))
#0 to 9 with step of 2
print(np.arange(0, 10, 2))
# 10 to 1, decresing order
print(np.arange(10, 0, -1))

[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[10  9  8  7  6  5  4  3  2  1]


In [57]:
# Start at 1 and end at 50
np.linspace(start=1, stop=50, num=10, dtype=int)

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

In [58]:
# Limit the number of digits after the decimal to 2
np.set_printoptions(precision=2)

# Start at 10^1 and end at 10^50
np.logspace(start=1, stop=50, num=10, base=10)

array([1.00e+01, 2.78e+06, 7.74e+11, 2.15e+17, 5.99e+22, 1.67e+28,
       4.64e+33, 1.29e+39, 3.59e+44, 1.00e+50])

In [59]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [60]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

# How to create repeating sequences?

In [61]:
a = [1,2,3]

# Repeat whole of 'a' two times
print('Tile: ', np.tile(a, 2))

# Repeat each element of 'a' two times
print('Repeat: ', np.repeat(a, 2))

Tile:  [1 2 3 1 2 3]
Repeat:  [1 1 2 2 3 3]


# How to generate random numbers?

In [62]:
# Random numbers between [0,1) of shape 2,2
print(np.random.rand(2,2))

# # Normal distribution with mean=0 and variance=1 of shape 2,2
print(np.random.randn(2,2))

# # Random integers between [0, 10) of shape 2,2
print(np.random.randint(0, 10, size=[2,2]))

# # One random number between [0,1)
print(np.random.random())

# # Random numbers between [0,1) of shape 2,2
print(np.random.random(size=[2,2]))

# # Pick 10 items from a given list, odd-even probability
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10))

# # Pick 10 items from a given list with a predefined probability 'p'
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10, p=[0.3, .1, 0.1, 0.4, 0.1])) # picks more o's

# # Create the random state
rn = np.random.RandomState(100)

# # Create random numbers between [0,1) of shape 2,2
print(rn.rand(2,2))

# # Set the random seed
# np.random.seed(100)

# # Create random numbers between [0,1) of shape 2,2
print(np.random.rand(2,2))

[[0.51 0.28]
 [0.6  0.87]]
[[ 0.55  0.94]
 [ 0.68 -0.45]]
[[1 6]
 [1 2]]
0.614314648126819
[[0.26 0.08]
 [0.84 0.51]]
['i' 'o' 'e' 'o' 'i' 'i' 'a' 'i' 'u' 'u']
['o' 'o' 'o' 'a' 'e' 'e' 'a' 'a' 'u' 'u']
[[0.54 0.28]
 [0.42 0.84]]
[[0.61 0.56]
 [0.84 0.41]]


In [63]:
# Create an array of 5x5 shape of elements from 10 to 100
mt=np.random.randint(50,100,size=[5,5])
mt

array([[98, 83, 72, 66, 80],
       [88, 60, 82, 89, 59],
       [63, 83, 51, 76, 95],
       [50, 67, 78, 67, 84],
       [96, 85, 68, 82, 56]])

# How to get the unique items and the counts?

In [64]:
# Create random integers of size 10 between [0,10)
np.random.seed(100)
arr_rand = np.random.randint(0, 10, size=10)
print(arr_rand)

[8 8 3 7 7 0 4 2 5 2]


In [65]:
# Get the unique items and their counts
uniqs, counts = np.unique(arr_rand, return_counts=True)
print("Unique items : ", uniqs)
print("Counts : ", counts)

Unique items :  [0 2 3 4 5 7 8]
Counts :  [1 2 1 1 1 2 2]


# How to handle datasets that has both numbers and text columns?

In [66]:
# import numpy as np
# data = np.genfromtxt('Auto.csv', delimiter=',', skip_header=1, filling_values=-999, dtype='float')
# data[:3] # see first 3 rows1.8000

In [68]:
# Save the array as a csv file
# np.savetxt("out.csv", data, delimiter=",")

# How to concatenate two numpy arrays columnwise and rowwise

In [69]:
a = np.zeros([4,4])
b = np.ones([4,4])
print(a)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [71]:
# vertical stack equivalents (row wise)
np.concatenate([a, b], axis=0)
np.vstack([a,b])
np.r_[a,b]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [73]:
# Horizontal stack equvalents (column wise)
np.concatenate([a,b], axis=1)
np.hstack([a,b])
np.c_[a,b]

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [74]:
np.r_[[1,2,3],0,0,[4,5,6]]

array([1, 2, 3, 0, 0, 4, 5, 6])

# How to sort a numpy array based on one or more columns?

In [77]:
arr = np.random.randint(1,6, size=[8,4])
arr

array([[4, 1, 2, 1],
       [5, 3, 1, 1],
       [3, 3, 2, 1],
       [3, 2, 5, 3],
       [1, 4, 4, 4],
       [1, 2, 5, 3],
       [4, 4, 5, 3],
       [5, 4, 2, 1]])

In [79]:
# Sort each columns of arr
np.sort(arr, axis=0)

array([[1, 1, 1, 1],
       [1, 2, 2, 1],
       [3, 2, 2, 1],
       [3, 3, 2, 1],
       [4, 3, 4, 3],
       [4, 4, 5, 3],
       [5, 4, 5, 3],
       [5, 4, 5, 4]])

# How to sort a numpy array based on 1 column using argsort?

In [81]:
# get the index positions that would sort the array
x = np.array([1,10,5,2,8,9])
sort_index = np.argsort(x)
print(sort_index)

[0 3 2 4 5 1]


In [82]:
x[sort_index]

array([ 1,  2,  5,  8,  9, 10])

In [83]:
# Argsort the first column
sorted_index_1stcol = arr[:, 0].argsort()
# Sort 'arr' by first column withut disturbing the integrity of rows
arr[sorted_index_1stcol]

array([[1, 4, 4, 4],
       [1, 2, 5, 3],
       [3, 3, 2, 1],
       [3, 2, 5, 3],
       [4, 1, 2, 1],
       [4, 4, 5, 3],
       [5, 3, 1, 1],
       [5, 4, 2, 1]])

In [84]:
# Descending sort
arr[sorted_index_1stcol[::-1]]

array([[5, 4, 2, 1],
       [5, 3, 1, 1],
       [4, 4, 5, 3],
       [4, 1, 2, 1],
       [3, 2, 5, 3],
       [3, 3, 2, 1],
       [1, 2, 5, 3],
       [1, 4, 4, 4]])

# Handling csv file using numpy

In [86]:
# data =np.genfromtxt('Auto.csv', delimiter=',',skip_header=1)
# data
# data.shape
# data.size
# data[:10,:5]
# sub_data=data[::3,:]
# sub_data
# sub_data.shape
# a=np.array([[1,2,3],[4,5,6],[7,8,9]])
# a
# np.delete(a,[1])
# sub_data=sub_data[:,:-1]
# sub_data
# np.info(sub_data)
# import matplotlib.pyplot as plt
# plt.plot(sub_data[:,0])
# plt.plot(sub_data[:,0],sub_data[:,-3])
# plt.scatter(sub_data[:,0],sub_data[:,-3], marker='^',color='y')
# plt.title("Sample Plot")
# plt.xlabel('X axis')
# plt.ylabel('Y axis')
# data=data[:,:-1]
# data
# np.savetxt('file.csv',data,delimiter=',')
